baseURL = "https://example.org/"
languageCode = "en-us"
title = "Leo's sharing space"

theme = "hugo-theme-stack"

[params]
    mainSections = "post"
    featuredImageField = "image"
    rssFullContent = true

[params.footer]
    since = 2025
    customText = "Leo's Blog"

[params.sidebar]
    emoji = "👍"
    subtitle = "Mathematics is the most beautiful tool we have made."

[params.sidebar.avatar]
    enabled = true
    local = false
    src = "https://i1.rgstatic.net/ii/profile.image/11431281228856658-1710248350364_Q128/Yao-Lei-2.jpg"